[package]
name = "humon-ebpf"
version = "0.1.0"
edition = "2021"

[dependencies]
humon-common = { path = "../humon-common" }
aya-ebpf = "0.1"
aya-log-ebpf = "0.1"

[[bin]]
name = "humon"
path = "src/main.rs"
